include:
  - project: 'strowi/ci-templates'
    file: '/build.yml'
  - project: 'strowi/ci-templates'
    file: '/tests.yml'

stages:
  - build
  - test
  - release

bbuild:
  extends: .build
  stage: build
  script:
    - build_image

container_scanning:
  extends: .container_scanning

dgoss:
  extends: .dgoss
  stage: test
  script:
    - dgoss_run $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG sleep 5s

release:
  extends: .build
  stage: release
  script:
    - release_latest
    - docker login -u "strowi" -p "$DOCKER_TOKEN" "docker.io"
    - docker tag "$CI_REGISTRY_IMAGE:latest" "strowi/alpine-squid"
    - docker push "strowi/alpine-squid"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

