---
variables:
  DOCKERHUB_USER: strowi

include:
  - project: 'strowi/ci-templates'
    file: '/build.yml'
  - project: 'strowi/ci-templates'
    file: '/tests.yml'
  - project: 'strowi/ci-templates'
    file: '/k3d.yml'

stages:
  - build
  - test
  - release


# "build_image"                        -> "${CI_REGISTRY_IMAGE}"
# "build_image $sub_image ./sub_dir/"  -> "${CI_REGISTRY_IMAGE}/sub_name
# always tagged + pushed with:release
#   - ":${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
#   - ":${CI_COMMIT_REF_SLUG}"
#   - ":latest" (NOT pushed, for building dependent images)
docker:build:
  extends: .build
  stage: build
  script:
    - build_image

container_scanning:
  extends: .container_scanning
  # parallel:
  #   matrix:
  #     - SUB_IMAGE_NAME:
  #       - /xyz

dgoss:test:
  extends: .dgoss
  script:
    - dgoss_run ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} sleep 5s

# "release_latest"                      -> "${CI_REGISTRY_IMAGE}"
# "release_latest./sub_dir/"            -> "${CI_REGISTRY_IMAGE}/sub_name
# push current "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}" as ":latest"
release_latest:
  extends: .build
  stage: release
  script:
    - release_latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - Dockerfile
    - when: never

# "release_tag"                      -> "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" + docker-hub
release_tag:
  extends: .build
  stage: release
  script:
    - release_tag
    - release_dockerhub
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile
    - when: never

deploy-tests:
  stage: test
  extends: .k3d
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  environment: ci
  script:
    - start_k3d
    - deploy-k8
    - get_pod nginx-krane
    - deploy-helm
    - get_pod nginx-helm
    - kubectl get deploy,po --all-namespaces
  parallel:
    matrix:
      - K3S_VERSION:
        - v1.28.9-k3s1
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      exists:
        - Dockerfile
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - Dockerfile
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
    - if: $CI_COMMIT_TAG
      when: never
