---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-krane
    team: sys
spec:
  selector:
    matchLabels:
      app: nginx-krane
      team: sys
  template:
    metadata:
      labels:
        app: nginx-krane
        team: sys
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-krane
    team: sys
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: nginx-krane
